//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesWebNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.DetailBIll = new HashSet<DetailBIll>();
        }
    
        public string idBill { get; set; }
        public string idUser { get; set; }
        public int Shipping { get; set; }
        public int totalMoney { get; set; }
        public string paymentMethod { get; set; }
        public string orderStatusID { get; set; }
        public System.DateTime createdAt { get; set; }
        public int quantity { get; set; }
        public string customerName { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string customerType { get; set; }
        public string note { get; set; }
        public string voucherID { get; set; }
        public int subTotal { get; set; }
        public string province { get; set; }
        public string district { get; set; }
        public string ward { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailBIll> DetailBIll { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
